app_name: we-mp-rss
cookie: 

#数据库连接 例如db:  mysql+pymysql://<username>:<password>@<host>/we-rss
db: ${DB:-sqlite:///db.db}

#通知
notice:
  dingding: "${DINGDING_WEBHOOK:-''}"
  wechat: "${WECHAT_WEBHOOK:-''}"
  feishu: "${FEISHU_WEBHOOK:-''}"
  
secret: ${SECRET_KEY:- 'we-mp-rss'}
token: 
user_agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.39...

#定时任务执行间隔时间 单位秒 默认300s
interval: ${INTERVAL:- 300}

#采集方式：web 或 api  默认web

model: ${MODEL:-web}

#是否采集内容  默认True
gather_content: ${GATHER_CONTENT:-True}

#API服务端口
port: ${PORT:-8001}
#调试模式
debug: ${DEBUG:-False}

#最大页数 第一次添加 采集的页数默认5页
max_page: ${MAX_PAGE:-5}

#RSS域名地址：如https://www.xxx.com
rss_base_url: ${RSS_BASE_URL:-""}