app_name: we-mp-rss
cookie: 

#数据库连接 例如db:  mysql+pymysql://<username>:<password>@<host>/we-rss?charset=utf8mb4
#需要注意数据库连接字符串的格式，如果是sqlite数据库，则使用sqlite:///路径的形式，如果是mysql数据库，
#则使用mysql+pymysql://<username>:<password>@<host>/<database>?charset=<数据库编码>的形式

db: ${DB:-sqlite:///data/db.db}

#通知
notice:
  dingding: "${DINGDING_WEBHOOK}"
  wechat: "${WECHAT_WEBHOOK}"
  feishu: "${FEISHU_WEBHOOK}"
  
secret: ${SECRET_KEY:- 'we-mp-rss'}
token: 
user_agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.39...

#定时任务执行间隔时间 单位秒 默认300s
interval: ${INTERVAL:- 300}

#采集方式：web 或 api  默认web

model: ${MODEL:-web}


#API服务端口
port: ${PORT:-8001}
#调试模式
debug: ${DEBUG:-False}

#最大页数 第一次添加 采集的页数默认5页
max_page: ${MAX_PAGE:-5}

rss:
  #RSS域名地址：如https://www.xxx.com
  base_url: ${RSS_BASE_URL:-""}
  #是否为本地RSS链接，默认True，当为False时直接出外部链接
  local: ${RSS_LOCAL:-True}

#登录会话有效时长 单位分钟 默认60分钟
token_expire_minutes: ${TOKEN_EXPIRE_MINUTES:-60}


gather:
  #是否采集内容  默认True
  content: ${GATHER.CONTENT:-True}
  #采集模式，web模式（可采集到发布链接)，api模式（可采集临时链接）
  model: ${GATHER.MODEL:-web}
log:
  #日志文件路径，默认为空字符串，表示不输出到文件。如果要输出到文件，可以指定一个路径如：/var/log/we-mp-rss.log 如果为空就不纪录
   file: ${LOG_FILE:-}
  #日志级别，默认为INFO，可选DEBUG, INFO, WARNING, ERROR, CRITICAL
   level: ${LOG_LEVEL:-INFO}