name: Docker Image Publish
on:
  push:
    branches:
      - main
    paths:  # 仅在指定文件变化时触发（可选）
      # - 'ReadMe.md'
      - '.github/workflows/docker-publish.yaml'
#   release:
#     types: [published]
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      # - name: Setup Node.js
      #   uses: actions/setup-node@v1
      #   with:
      #     node-version: '20.18.3' # 替换为你的项目所需的 Node.js 版本
      # - name: Build Web UI
      #   run: |
      #     cd ./web_ui
      #     chmod +x build.sh
      #     ./build.sh

      - name: Log in to GHCR
        run: echo  ${{secrets.TOKEN}} | docker login ghcr.io -u  ${{github.actor}} --password-stdin
      - name: Build Docker Image
        run: docker build -t ghcr.io/${{github.repository}}:beta-${{github.ref_name}} .
      - name: Push Docker Image
        run: docker push ghcr.io/${{github.repository}}:beta-${{github.ref_name}}