name: Release Zip
on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Zip
        # 添加构建项目的步骤
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          token:  $ {{ secrets.TOKEN }}
          # 其他可选配置，如发布说明文件、附加文件等